server:
  port: 88

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: after_route
          uri: http://localhost:6000/member/member/test1
#          uri: http://www.baidu.com
          predicates:
            - Query=url,test

  application:
    name: gulimall-gateway